name: Build Calendar

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31

      - name: Build binary
        run: nix develop --command just prod

      - name: Run generator
        run: nix develop --command sh -c './calendar-holidays-generator'

      - name: Upload calendar artifacts
        uses: actions/upload-artifact@v4
        with:
          name: calendar-ics-files
          path: output/*ics
